#!/bin/bash
SCRIPTPATH=$(readlink -f $0)
SCRIPTDIR=$(dirname $SCRIPTPATH)
APPDIR=$(dirname $SCRIPTDIR)

echo Creating container
CONTAINERID=$(docker run -d noteed/hakyll https://github.com/rcook/seattlehaskell-org.git)
if [ $? -ne 0 ]; then
  echo Docker failed
fi

echo Waiting for Hakyll to complete
docker wait $CONTAINERID > /dev/null
if [ $? -ne 0 ]; then
  echo Hakyll failed
fi

echo Copying generated web site
docker cp $CONTAINERID:/home/hakyll/clone/_site $APPDIR > /dev/null
if [ $? -ne 0 ]; then
  echo Copy failed
fi

echo Removing container
docker rm $CONTAINERID > /dev/null
if [ $? -ne 0 ]; then
  echo Remove failed
fi

