#!/bin/bash
set -e
if [[ "$OSTYPE" =~ ^darwin ]]; then
  READLINK=greadlink
else
  READLINK=readlink
fi
THISPATH=$($READLINK -f $0)
THISDIR=$(dirname $THISPATH)
PROJECTDIR=$(dirname $THISDIR)

if [[ ! "$1" =~ ^([A-Za-z]+)(\.[A-Za-z]+)*$ ]]; then
  echo Specify domain
  exit 1
fi
DOMAIN=$1
shift

if [[ "$1" == "" ]]; then
  echo Specify proxy port
  exit 1
fi
PROXYPORT=$1
shift

if [[ "$1" == "" ]]; then
  echo Specify document root
  exit 1
fi
DOCROOT=$(readlink -f $1)
shift

cat config/apache2.conf.template | \
  sed -e "s/\$DOMAIN/$DOMAIN/g" \
    -e "s/\$PROXYPORT/$PROXYPORT/g" \
    -e "s#\$DOCROOT#$DOCROOT#g"
