#!/bin/bash
set -e
if [[ "$OSTYPE" =~ ^darwin ]]; then
  READLINK=greadlink
else
  READLINK=readlink
fi
THISPATH=$($READLINK -f $0)
THISDIR=$(dirname $THISPATH)
PROJECTDIR=$(dirname $THISDIR)

cd $PROJECTDIR
stack exec -- yesod keter
