#!/bin/bash
SCRIPTPATH=$(readlink -f $0)
SCRIPTDIR=$(dirname $SCRIPTPATH)
APPDIR=$(dirname $SCRIPTDIR)

cd $APPDIR

cabal build
if [ $? -ne 0 ]; then
  echo cabal build failed
  exit 1
fi

$APPDIR/dist/build/site/site rebuild
if [ $? -ne 0 ]; then
  echo site build failed
  exit 1
fi

